# Generated by Django 6.0.2 on 2026-03-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RemoveField(
            model_name='author',
            name='salutation',
        ),
    ]
